name: dot_navigation_bar
description: A bottom navigation bar that you can customize with the options you need, without any limits. You can also customize the appearance of the navigation bar with simple smooth animations, providing a nice and clean UX.
version: 0.0.1
# author: Haptome <haptomee@gmail.com>
homepage: https://github.com/haptome/dot_navigation_bar

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  line_awesome_flutter: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  
